# Generated by Django 3.2.17 on 2023-05-01 17:18

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('seq', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255, null=True)),
                ('post_id', models.CharField(max_length=255, null=True)),
                ('file_id', models.CharField(max_length=255, null=True)),
                ('kkk', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='file',
            old_name='img_key',
            new_name='file_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='created',
        ),
        migrations.RemoveField(
            model_name='file',
            name='img_fullfname',
        ),
        migrations.RemoveField(
            model_name='file',
            name='img_state',
        ),
        migrations.RemoveField(
            model_name='file',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_video',
        ),
        migrations.RemoveField(
            model_name='file',
            name='uploaded',
        ),
        migrations.RemoveField(
            model_name='file',
            name='video_fullfname',
        ),
        migrations.RemoveField(
            model_name='file',
            name='video_key',
        ),
        migrations.RemoveField(
            model_name='file',
            name='video_state',
        ),
        migrations.RemoveField(
            model_name='file',
            name='video_url',
        ),
        migrations.AddField(
            model_name='file',
            name='kkk',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
