# Generated by Django 3.2.17 on 2023-05-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20230513_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='post_id',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='file',
            name='kkk',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user_id',
        ),
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='media_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
